# Stage 1: Build kode React/Vue/Vite
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Jalankan dengan Nginx
FROM nginx:stable-alpine
# PENTING: Jika folder hasil build temanmu bukan 'dist' (misal 'build'), ganti tulisan dist di bawah
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]