name: Build and Cross-Browser Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Docker Images
        run: |
          touch .env
          docker compose build

      - name: Install Playwright
        run: |
          npm install -g playwright
          npx playwright install --with-deps

      - name: Final Success Check
        run: echo "Infrastruktur DevOps Berhasil Dikonfigurasi!"